name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the site and deploy
      run: |
        # Build your site here if needed, for example, using Jekyll, Hugo, etc.
        # Then deploy to GitHub Pages
        git remote add origin https://github.com/${{ github.repository }}.git
        git add .
        git commit -m "Deploy update"
        git push origin main
